### ISSUE TITLE
Error while reading .aasx in basyx

### ISSUE THREAD

**Issue by jorgegomezjumh** [LukasBenner/AASFix#23]
I have used your AASFix to fix my AASX Package Explorer File, and I didn´t get the same error that I had before and my script run, but has the following errors:

![image](https://github.com/LukasBenner/AASFix/assets/121818662/4e7c5a69-1c88-41e9-8169-f0079079ffbc)

PS:  My .aasx is from AASX Package Explorer v3. And I have navigate through the new_object_store and is empty.

**Comment by LukasBenner** [comment]
Which exact version of the AASX Package Explorer did you use?

If you unzip your .aasx file with e.g. 7zip, you can take a look at the raw files. 
The file `aasx\<someName>\<someName>.aas.xml` is the file you are looking for.
The topmost xml tag should be `<environment xmlns="https://admin-shell.io/aas/3/0">`.

**Comment by jorgegomezjumh** [comment]
I have been using 'aasx-package-explorer.2023-09-12.alpha.' However, I recently tried 'aasx-package-explorer.2023-11-17.alpha' along with AASFix, and encountered new errors:

![image](https://github.com/LukasBenner/AASFix/assets/121818662/daf84c12-38f9-4216-8572-5f263b69dd7e)

I have also saved the same AASX file that I use in AASFix in XML format to inspect these lines, and this is what appears to me:

![image](https://github.com/LukasBenner/AASFix/assets/121818662/6ff12112-dc16-4e97-930e-e737bfedd883)

**Comment by WelliSolutions** [comment]
From the screenshot in the original post, it looks like the file uses AAS version 2. AASFix will not convert files between versions. Package Explorer can do that.

From the second screenshot, it looks like the file uses AAS version 3. That should be fine for the Python basyx library 1.0.0. At the moment I can't tell what's wrong, since I don't know how the library determines the class name from the XML structure.

Is your AASX file secret, or could you upload it, so that I can have a closer look? You don't seem to work on a [sample file](https://admin-shell-io.com/samples/).

**Comment by jorgegomezjumh** [comment]
I have tried to use the AASX file from samples and also the one from content for the demo. I have also eliminated the sensitive information from the '5G_UE_AAS_V3' for sharing with you. I have attached the file before and after AASFix, along with a capture showing the different errors that appear to me.

![image](https://github.com/LukasBenner/AASFix/assets/121818662/9031b702-2b7c-4e09-8818-7cd0a942624d)


[5G_UE_AASX_V3_FILES.zip](https://github.com/LukasBenner/AASFix/files/13938527/5G_UE_AASX_V3_FILES.zip)

**Comment by LukasBenner** [comment]
So, the first two screenshots give the impression that you are using example files that are not from AAS version 3.0.
Your should upgrade the files to version 3.0 by opening and storing them with the AASX Package Explorer.

Secondly, I was able to find some issues in your AASX file.

1.  It seems like the basyx SDK doesn't like empty semanticIDs. An empty semanticID looks like this:
  ![grafik](https://github.com/LukasBenner/AASFix/assets/36197800/ea371e40-552d-4fe7-8684-ead28e177420) In the xml an empty semanticID looks like this :
    ```
    <semanticId>
      <type>ExternalReference</type>
      <keys>
        <key>
          <type>GlobalReference</type>
          <value>https://admin-shell.io/sandbox/SG2/TechnicalData/GeneralInformation/1/1</value>
        </key>
      </keys>
    </semanticId>
    ```
2. You can't have a semanticID of type ExternalReference, referencing a Submodel. You have to use a GlobalReference instead. This is the case for your Submodels "Identification", "Documentation" and "TechnicalData"
![grafik](https://github.com/LukasBenner/AASFix/assets/36197800/593c7c7d-8918-46b2-afbd-4603fad3988c)

3. I removed your ConceptDescriptions because they seemed a bit messed up. (The AASX Package Explorer showed some warnings and errors)

After fixing these Problems i was able to open your file with the basyx sdk.
I still got the error "AttributeError module 'encodings.cp437' has no attribute 'getaliases'", but setting failsafe=False resolved the issue `reader.read_into(object_store=object_store, file_store=file_store, failsafe=False)`.

I attached the altered files
[5G_UE_AAS_V3_altered.zip](https://github.com/LukasBenner/AASFix/files/13998245/5G_UE_AAS_V3_altered.zip)

**Comment by WelliSolutions** [comment]
Nice analysis, Lukas. Let's implement 1. and 2., then close this issue.

**Comment by jorgegomezjumh** [comment]
Hi, thank you for your attention but it doesn´t work for me.

First of all, I have tried to use your altered files and this appears to me:

![image](https://github.com/LukasBenner/AASFix/assets/121818662/4b8db070-0d89-435a-9e29-c4f5d982c58d)

Then I have tried to put a semanticID to every single element in the AAS (Submodels, SubmodelElementCollection,SubmodelElementList,Property...) and the semanticId beeing of kind "ExternalReference" "GlobalReference" and for a reason I don´t understand the AASFix don´t fix this problem and this error appears to me again:

 
![image](https://github.com/LukasBenner/AASFix/assets/121818662/b6aedf4b-180f-4e47-9326-667ef3ee8fcf)

So, I decide to try changing only a few elements and AASFix, fix these problems and this is the error that appears (But the object_store seems to be saving something):

![image](https://github.com/LukasBenner/AASFix/assets/121818662/24b44aac-dd3f-4a6c-b05b-4012c003a331)

After that, I have tried to use the failsafe and now I have this error:
![image](https://github.com/LukasBenner/AASFix/assets/121818662/9104d663-88be-4384-87fb-e51d93a385bd)


I don´t know more things to probe to make it work, and I don´t know more information to give you.

My basyx-python environment is in this file: C:\Users\uwicore\basyx-python-sdk-main\basyx-python-sdk-main\basyx\aas

I have been using this version of basyx:
[basyx-python-sdk-main.zip](https://github.com/LukasBenner/AASFix/files/14050682/basyx-python-sdk-main.zip)

And this basyx is using this file to execute the actions:
C:\Users\uwicore\anaconda3\Lib\site-packages\aas

And this file contains:
[aas.zip](https://github.com/LukasBenner/AASFix/files/14050763/aas.zip)

Thank you for all your help in advance.

**Comment by jorgegomezjumh** [comment]
Hi, have you found any possible solution for this problem?
Can I contact you for another way to be faster? 

Thank you in advance.

**Comment by LukasBenner** [comment]
I believe there might be a minor misunderstanding. 

My colleague and I are currently working on a tool aimed at resolving inconsistencies between the AASX Package Explorer and the basyx-sdk. This tool helps us to improve our own workflow.

My suggestion for you is, to start with a very basic example and work your way up from there. 
Unfortunately, it seems the root of the issue might lie within the basyx-sdk and your AASX file.

Nevertheless I will implement a fix for the inconsistencies mentioned here:

> So, the first two screenshots give the impression that you are using example files that are not from AAS version 3.0. Your should upgrade the files to version 3.0 by opening and storing them with the AASX Package Explorer.
> 
> Secondly, I was able to find some issues in your AASX file.
> 
>     1. It seems like the basyx SDK doesn't like empty semanticIDs. An empty semanticID looks like this:
>        ![grafik](https://private-user-images.githubusercontent.com/36197800/298286596-ea371e40-552d-4fe7-8684-ead28e177420.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNjEyNTcsIm5iZiI6MTcwNzE2MDk1NywicGF0aCI6Ii8zNjE5NzgwMC8yOTgyODY1OTYtZWEzNzFlNDAtNTUyZC00ZmU3LTg2ODQtZWFkMjhlMTc3NDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE5MjIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMjc3MDE4NGVmY2NlMDA3YTY4OGIwOWJjMmQ4NzIzZWM4OTI5ZDliYzNjYjcxNDhjNzg4NTdkMjAyMmI5ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uHByItCWLunmfG-O4Zaag_XKgHzQW22IogW52Jwf70w) In the xml an empty semanticID looks like this :
>        ```
>        <semanticId>
>          <type>ExternalReference</type>
>          <keys>
>            <key>
>              <type>GlobalReference</type>
>              <value>https://admin-shell.io/sandbox/SG2/TechnicalData/GeneralInformation/1/1</value>
>            </key>
>          </keys>
>        </semanticId>
>        ```
> 
>     2. You can't have a semanticID of type ExternalReference, referencing a Submodel. You have to use a GlobalReference instead. This is the case for your Submodels "Identification", "Documentation" and "TechnicalData"
>        ![grafik](https://private-user-images.githubusercontent.com/36197800/298286979-593c7c7d-8918-46b2-afbd-4603fad3988c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNjEyNTcsIm5iZiI6MTcwNzE2MDk1NywicGF0aCI6Ii8zNjE5NzgwMC8yOTgyODY5NzktNTkzYzdjN2QtODkxOC00NmIyLWFmYmQtNDYwM2ZhZDM5ODhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE5MjIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YjNjNzRjZWJmYTJhODgzYzU3YjJmMzMzZGE3YjJiMjExNWY3ODM0YzJhN2I5ZTNkNzViMTNmYzQ0NDI0NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yeQX2zGFh1HMmn5IW_uAUXJ7E_5-RirG_wDh8jf1uQw)
> 
>     3. I removed your ConceptDescriptions because they seemed a bit messed up. (The AASX Package Explorer showed some warnings and errors)
> 
> 
> After fixing these Problems i was able to open your file with the basyx sdk. I still got the error "AttributeError module 'encodings.cp437' has no attribute 'getaliases'", but setting failsafe=False resolved the issue `reader.read_into(object_store=object_store, file_store=file_store, failsafe=False)`.
> 
> I attached the altered files [5G_UE_AAS_V3_altered.zip](https://github.com/LukasBenner/AASFix/files/13998245/5G_UE_AAS_V3_altered.zip)

**Comment by jorgegomezjumh** [comment]
I've reviewed the solution incorporating all the information you provided in this matter, along with the guidance from the basyx team. It appears that the root cause was indeed incorrect files, as mentioned in this issue: https://github.com/eclipse-basyx/basyx-python-sdk/issues/19

**Comment by jorgegomezjumh** [comment]
Thank you for all your help.

**Comment by LukasBenner** [comment]
Great, glad you were able to resolve the issue. I'll close this one.
